//
//  MyStyleKit.h
//  vBox
//
//  Created by Rosbel Sanroman on 11/30/14.
//  Copyright (c) 2014 Rosbel. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// Colors
+ (UIColor*)myOrange;
+ (UIColor*)mySkyBlue;

// Drawing Methods
+ (void)drawVBoxButtonWithButtonColor: (UIColor*)buttonColor;

// Generated Images
+ (UIImage*)imageOfVBoxButtonWithButtonColor: (UIColor*)buttonColor;

@end
