//
//  MyStyleKit.h
//  vBox
//
//  Created by Rosbel Sanroman on 11/30/14.
//  Copyright (c) 2014 Rosbel. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* startTripButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* drivingHistoryButtonTargets;

// Drawing Methods
+ (void)drawStartTripButton;
+ (void)drawDrivingHistoryButton;

// Generated Images
+ (UIImage*)imageOfStartTripButton;
+ (UIImage*)imageOfDrivingHistoryButton;

@end
