//
//  StyleKitIcons.h
//  vBox
//
//  Created by Rosbel Sanroman on 11/28/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitIcons : NSObject

// Drawing Methods
+ (void)drawSpeedometerWithColor: (UIColor*)color;

// Generated Images
+ (UIImage*)imageOfSpeedometerWithColor: (UIColor*)color;

@end
