//
//  StyleKitIcons.m
//  vBox
//
//  Created by Rosbel Sanroman on 11/28/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitIcons.h"


@implementation StyleKitIcons

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawSpeedometerWithColor: (UIColor*)color
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Group
    {
        //// Oval Drawing
        UIBezierPath* ovalPath = UIBezierPath.bezierPath;
        [ovalPath moveToPoint: CGPointMake(48, 35.81)];
        [ovalPath addCurveToPoint: CGPointMake(41.91, 20.35) controlPoint1: CGPointMake(48, 29.84) controlPoint2: CGPointMake(45.69, 24.41)];
        [ovalPath moveToPoint: CGPointMake(30.81, 13.73)];
        [ovalPath addCurveToPoint: CGPointMake(25, 13) controlPoint1: CGPointMake(28.95, 13.25) controlPoint2: CGPointMake(27.01, 13)];
        [ovalPath addCurveToPoint: CGPointMake(2, 35.81) controlPoint1: CGPointMake(12.3, 13) controlPoint2: CGPointMake(2, 23.21)];
        ovalPath.lineCapStyle = kCGLineCapRound;

        [color setStroke];
        ovalPath.lineWidth = 4;
        [ovalPath stroke];


        //// Bezier 2 Drawing
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 27.31, 28.24);
        CGContextRotateCTM(context, 10.82 * M_PI / 180);

        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(8.39, -13.04)];
        [bezier2Path addCurveToPoint: CGPointMake(2.41, 6.29) controlPoint1: CGPointMake(8.39, -13.04) controlPoint2: CGPointMake(2.71, 6.45)];
        [bezier2Path addCurveToPoint: CGPointMake(-1.54, 8.84) controlPoint1: CGPointMake(1.69, 7.8) controlPoint2: CGPointMake(0.19, 8.84)];
        [bezier2Path addCurveToPoint: CGPointMake(-5.95, 4.23) controlPoint1: CGPointMake(-3.97, 8.84) controlPoint2: CGPointMake(-5.95, 6.78)];
        [bezier2Path addCurveToPoint: CGPointMake(-5.48, 2.17) controlPoint1: CGPointMake(-5.95, 3.49) controlPoint2: CGPointMake(-5.78, 2.79)];
        [bezier2Path addCurveToPoint: CGPointMake(8.39, -13.04) controlPoint1: CGPointMake(-5.78, 2.02) controlPoint2: CGPointMake(8.39, -13.04)];
        [bezier2Path addLineToPoint: CGPointMake(8.39, -13.04)];
        [bezier2Path closePath];
        [color setFill];
        [bezier2Path fill];

        CGContextRestoreGState(context);
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfSpeedometerWithColor: (UIColor*)color
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 50), NO, 0.0f);
    [StyleKitIcons drawSpeedometerWithColor: color];

    UIImage* imageOfSpeedometer = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSpeedometer;
}

@end
